# -*- coding: utf-8 -*-
"""distancia entre dos puntos a la tierra

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mjJwAGX_DYjFl5jPTWpd2eq4pCIacmSw
"""

alt1=float(input())
la1=float(input())
alt2=float(input())
la2=float(input())

import math

t1= math.radians(alt1)
t2= math.radians(alt2)
g1= math.radians(la1)
g2= math.radians(la2)


from math import acos, asin, cos, sin

distancia = 6371.01 * acos(sin(t1)*sin(t2) + cos(t1)*cos(t2)*cos(g1-g2))

print(distancia)

